### ISSUE TITLE
Please tell me why I need to use `from roboduck import *`?

### ISSUE THREAD

**Issue by yupix** [fotoente/MIsskey-ebooks-bot#16]
It is not recommended to use `from roboduck import *` for several reasons. There are several reasons for this, but in this case, the library imported by roboduck will be imported by rdbot, which makes it difficult to know which module depends on which library. If there is no intention, send a pull request.

**Comment by fotoente** [comment]
I really can't tell you anymore...

This is still one of my earliest Python projects, so there will be old stupid misstakes in here...

**Comment by yupix** [comment]
Okay, I will send a pull request when I have time.

**Comment by fotoente** [comment]
Changed to `import roboduck` in bc9121f812c211ca90c6e5b8d3e3382d41d0517c
