### ISSUE TITLE
Bot reaches 100% CPU

### ISSUE THREAD

**Issue by fotoente** [fotoente/MIsskey-ebooks-bot#2]
During catching new notes the Bots max out the CPU and get stuck

**Comment by vibikim** [comment]
I ran the bot in foreground then interrupted with ^C a little while after it got stuck. So you can take a look at the output. Not sure if it's of any help
[ebooks-stdout.txt](https://github.com/fotoente/MIsskey-ebooks-bot/files/7847346/ebooks-stdout.txt)

There is another time when I stopped it right when it  crashed. The point when it did that was at the `Posts loaded!` line and the traceback looked the same.

**Comment by fotoente** [comment]
Hmm interessting.
THe `Post loaded!` is just a hint for you that the function finished where he loaded all the notes you asked him to do.
After that he claculates the markov chain and puts that into a object that the bots saves into his memory.

Then her normaly calculates a sentence and posts that, and by the timestamps I can see that this happens right after he catched the last X Notes after 12 hours (posts refresh cycle)

So it seems like every time when he recalculates your markov chain the sentence creation fails/get stuck in a loop.

Is your RAM maxed out at that point? It is very RAM heavy because of the huge amount of text the markov chain processes...

**Comment by fotoente** [comment]
Another user with the same problem got this behaviour:
>or me it wouldn't even finish loading posts the majority of the time, and the 100% cpu would spin while one of the websocket connections in Mi waits endlessly or something

Source: https://misskey.bubbletea.dev/notes/8vos2yqh0a

**Comment by fotoente** [comment]
```
Traceback (most recent call last):
  File "/home/ente/.local/lib/python3.9/site-packages/mi/ext/tasks/__init__.py", line 50, in task
    await self.func(self.seconds, *args, **kwargs)
  File "/home/ente/roboduck/rdbot.py", line 38, in loop_12h
    bot.text_model = read_posts()
  File "/home/ente/roboduck/roboduck.py", line 46, in read_posts
    notes_count = int(int(config.get("markov","notes_count"))/100)
  File "/usr/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'notes_count' in section: 'markov'
```

I am not sure why, but it seems like there is an error reading the config file. He can't find the number of how many posts to read

**Comment by fotoente** [comment]
Found the bug!
The regular expression to remove the instance name from a post breaks sometimes...

I know need a way to fix that

**Comment by fotoente** [comment]
The Problem was with this regular expression `@([a-zA-Z0-9-]*(\.)?)*[a-zA-Z0-9-]*\.[a-zA-z]*`
It lead to a infinite loop in the traceback when the username was too long and contained dashes

Simple fix is just to use `@([a-zA-Z0-9-]*(\.))*[a-zA-Z0-9-]*\.[a-zA-z]*`
